### PR TITLE
Feature/qk8s-54: split qTest Manager into 4 separated role-based pod

### PR DESCRIPTION
**Pull request by duypm**
The change in this pull request go hand in hand with the change from within qTest Manager web application, which can be reviewed in detail at https://git.qasymphony.com/qtest/test-conductor/compare/0f107c9f28e43a49539a0ffb4ec3faea6bc09367...ccd27d6acfde04ad205c13dbab1477d39176ee40

### CODE REVIEW

**Review by pjaladi21 — APPROVED** [review]

**Comment by byangtri** [comment]
@duypm you have done the changes in deployment.yaml but same changes needs to be made to rollout.yaml

**Comment by duypm** [comment]
Thanks @byangtri I will update that in QK8S-305

**Comment by duypm** [comment]
@byangtri for QK8S-305, I have updated rollout.yaml to add Rollout for API and Notification Pod. However, I'm not sure how to deal with the Poller Pod since that one has no Service and both BlueGreen and Canary strategy is asking for one. Do I need to create a dummy Service for that to work?

**Review by byangtri — CHANGES_REQUESTED** [review]
ingress.yaml needs to be updated with the new service name and path changes

**Review by byangtri — APPROVED** [review]

**Comment by byangtri** [comment]
Hi @duypm  @pjaladi21  Can we seperate each pods to have their own resources (CPU and Memory) or would they be required to use the same

**Comment by duypm** [comment]
With the current PROD, they all have the same resources specs (CPU & Mem). Only their replica number is different. The thing with JVM app is you need to match their Xmx and Xms parameters with the available resource of the container, to avoid under utilization or running into unexpected OOM error. Right now those params is controlled in the Dockerfile among with many other JVM params so we also need to make change there first to allow fine tuning Xmx and Xms from the template level without accidentally override other JVM config.

**Pull request merged**
