### PR TITLE
update rollout and ingress

### PR DESCRIPTION
**Pull request by byangtri**

### CODE REVIEW

**Comment by byangtri** [comment]
I made some slight changes to ingress and rollout.yaml. Ingress syntax you used was another api version (apiVersion: networking.k8s.io/v1), however we are using (apiVersion: networking.k8s.io/v1beta1).
For rollout.yaml I added poller. This should be able to run however I have not tested

**Review by duypm — APPROVED** [review]
Thanks for the update @byangtri I had no idea about the API version here and was pulling my hair off early today trying to resolve this exact issue with my local Ingress (my fault for not paying attention).
However, you were a little off with the poller Rollout so I add a commit correcting those.

**Comment by byangtri** [comment]
Hey Duy, I pulled the poller code straight from deployment.yaml. Please make those same corrections for the poller deployment in deployment.yaml

**Comment by byangtri** [comment]
@duypm  I went ahead and fixed the deployment app labels for Api and Poller. Please review and merge

**Pull request merged**
