### PR TITLE
Feature/qk8s-302: Add Signal Sciences as sidecar for qTest Manager Pod

### PR DESCRIPTION
**Pull request by duypm**
See more detail of the technical approach in https://jira.tricentis.com/browse/QK8S-302 comments.

### CODE REVIEW

**Comment by duypm** [comment]
@byangtri do you know anyway to make Rollout.template.spec refers to the Deployment.template.spec instead of having the same containers snippet duplicate between the 2 files?

**Review by byangtri — CHANGES_REQUESTED** [review]
For ingress values, IngressClassName and annotations are currently in use for Rollouts.yaml

**Comment by byangtri** [comment]
> @byangtri do you know anyway to make Rollout.template.spec refers to the Deployment.template.spec instead of having the same containers snippet duplicate between the 2 files?

To reference a deployment, you can use [workloadRef](https://gist.github.com/jessesuen/435e8b77728af2fc73ca87323915deb2#file-guestbook-rollout-yaml-L7) to the deployment.

**Comment by duypm** [comment]
I have also submitted change to Dev values, to add SigSci sandbox key in https://github.com/QAS-Labs/aws-qtest-k8/pull/16

**Comment by byangtri** [comment]
Hi @duypm I see you changed `- containerPort: {{ .Values.service.port }}` to `- containerPort: 8080` instead of referencing the port in values.yaml. If you believe we do not need to allow the port to be configured in values.yaml, then you can go ahead and remove the service.port value in values.yaml. 
In secret.yaml, we would need to allow the qtest-sigsci-secret to be overridden by an existing secret, we would not want the secret key to be exposed in github as we are keeping all secrets in [external secrets ](https://github.com/QAS-Labs/aws-qtest-k8/tree/main/kubernetes/secrets-dev)

**Review by byangtri — COMMENTED** [review]
> Hi @duypm I see you changed `- containerPort: {{ .Values.service.port }}` to `- containerPort: 8080` within the deployment/rollout manifest instead of referencing the port in values.yaml. If you believe we do not need to allow the port to be configured in values.yaml, then you can go ahead and remove the service.port value in values.yaml.
> In secret.yaml, we would need to allow the qtest-sigsci-secret to be overridden by an existing secret, we would not want the secret key to be exposed in github as we are keeping all secrets in [external secrets ](https://github.com/QAS-Labs/aws-qtest-k8/tree/main/kubernetes/secrets-dev)

**Comment by duypm** [comment]
@byangtri although I don't think the container port will ever need to be configurable (at least from the end-user perspective), using Values rather than a hard-coded value seem nicer in term of code organization and maintainability so I switched back as you have suggested.

I have also made the change so that SigSci secret can now accommodate for ExternalSecret, which I have also create a separate PR for in https://github.com/QAS-Labs/aws-qtest-k8/pull/16. I'm not sure how the actual secret is created in AWS SecretManager so I have use AWS CLI to create one first at `arn:aws:secretsmanager:us-east-1:242129367204:secret:signalSciencesKey-dev-qezCp3`

**Pull request merged**
